# -*- coding: utf-8 -*-
"""Assignment1_TuteDude.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b7jbWu4altAeRp4aD_MqAuuMpalXmZr1
"""

var1 = input('Enter the first number:')
var2 = input('Enter the second number:')
addition = int(var1) + int(var2)
print("Addition",addition)
subtraction = int(var1) - int(var2)
print("Subtraction", subtraction)
multiplication = int(var1) * int(var2)
print("Multiplication", multiplication)
division = int(var1) / int(var2)
print("Division", division)

first_name = input("Enter your first name:" )
second_name = input("Enter your second name:" )
#print('Hello, first_name,second_name! 'Welcome to the python program')
print("Hello ", first_name, second_name,"!" "Welcome to the python program")